### PR TITLE
Feature/featured favorites

### PR DESCRIPTION
**Pull request by oskarrough**
Changes the channels shown on the homepage aka `channels.index` aka "Featured".

It will now show `3 random favorites * 4 random featured channels`.

- [x] Find X random featured channels

Preview (try to refresh!) https://feature-featured-favorites--radio4000.netlify.com

### CODE REVIEW

**Comment by oskarrough** [comment]
What to do with this again? Merge it? Or improve it with a shallow query for featured channels and take 5 random ones to make it more dynamic?

**Comment by hugurp** [comment]
# Feature:
1- in the admin backend we select which channels are `isFeatured`, as much interesting channels as possible (in the future we need to find a way that this system does not require admin help, automatic/user-selected)
2- then in the `/` route we define how much channels (`x`) we want to query from `channels.findAll('isFeatured', {limitToLast: x })`
3- from this channels we randomly select `y` favorites.

## Pros:
- more dynamic homepage

## Cons:
- slower load
- we have to be sure the `channels.isFeatured.favorites` have enough tracks


# Alternative feature
1- define as many `channels.isFeatured` as possible
2- query `x` of them, and make the query be different each time. Ex: start at `x`, end at `y` in the query, with x and y < channels.isFeatured.length

**Comment by hugurp** [comment]
I'm not sure what to do about this one.

What are the final objectives?
- make the homepage more dynamic
- make the selection more diverse
- make the selection more independant of admins

What more?
What are the neatiest ways to achieve these?

**Comment by oskarrough** [comment]
> make the selection more independant of admins

Also interesting but we can tackle that in a future issue?

Currently this PR

- adds methods to fetch featured channels AND the favorites of those
- adds props to control how many featured AND how many random favorites from each featured channel we fetch

It's not so slow that we can not go for it as-is, in my opinion. One thing is that we only show the favorites from each featured so the featured channels themselves are actually never shown. Unless they by coincidence are a favorite of another featured radio. An easy solution to this could be to show:

- A collection of X random favorites from Y latest featured channels + 1-3 from Y?

**Comment by hugurp** [comment]
realy good changes, lgtm!

**Pull request merged**
