### PR TITLE
Feature/improve signup

### LINKED ISSUE #191: Add missing `create your radio` button on homepage (when logged out)
We don't explain to logged out users that they can, not only listen to existing radios, but create their.

One way it is good, so only people who really want to join will make the effort to connect and create their radio.

But we never explain that there is a possibility, except in the about page.

Maybe just adding a `create your radio` button with the two other buttons would be enough.
Button that is a link to sign up.

Therefore, we maybe have to improve the signup page with some explicative text, "why you would sign up", to create a radio and so on.

### PR DESCRIPTION
**Pull request by oskarrough**
The goal of this PR is to make it the process of creating a radio more visible for new users. See the discussion in #191.

It's a work in progress. As always, feedback, changes and experiments welcome.

Fixes #191

### CODE REVIEW

**Comment by oskarrough** [comment]
@lucho1112 @hugurp how about this?

- renamed button in menu: https://feature-improve-signup--radio4000.netlify.com
- played around with layout and wording on signup page: https://feature-improve-signup--radio4000.netlify.com/auth/signup

**Comment by lucas1288** [comment]
Big improvement overall. 
Nothing to say about the sign-up page, quite clear to me.

About the homepage though: I see that two buttons are basically doing the same action:
- "Create radio" purple button in the menu
- "Create my radio" under the "start listening" button with an explanatory text

Does it make sense to you guys if we just kill one of the two? I would keep the purple one the side and have the explanatory text just above.

**Comment by hugurp** [comment]
The one button on the home page is only on this page.

The button on the aside is there all the time, because the aside stays visible.
Except on mobile, where it is hiden by default (and toggled visible with the burger menu).

Therefore if we remove the button on the homepage, there won't be a button except on the aside (that would have to be toggled visible).

Not sure what is better between:
- [ ] actual solution, 2 buttons
- [ ] remove button on /home
- [ ] hide button on /home, when it is on desktop (aka, when aside is visible by default)

opinions?

Is there an other solution that i don't see?

What is the purpose of this button? Do we really need it? Is there a better way to explain users that they can create their own radio, in general over all the pages?

**Comment by oskarrough** [comment]
Yea I see what you mean. We could either change to text links (from button). Or remove them, since they repeat the main navigation anyway. @hugurp?

Four tests

test4

test3

test33

test

**Comment by hugurp** [comment]
Interesting overview, and suggestions.
I actually am not sure here. Maybe that is where a a/b/c/d testing could help, or a user test looking behind someone's shoulder.

The simplest and more coherent solution seems to be hidding the home create radio button on desktop and showing it on mobile.

I'll try to sleep on it see if this discussion can fit but into a bigger problematic.

**Comment by hugurp** [comment]
We should add "Welcome to Radio4000!", instead of just "Welcome!", since we never mention the name but in the URL.

**Comment by oskarrough** [comment]
Good point about mobile, didn't consider. I removed the extras on /search. On the homepage it's now a little text, which adapts depending on whether you are signed in already or not. I think this can work for now and the PR already improves sign up quite a lot. Merge?

First you see this

without radio

then you see this

with radio

**Pull request merged**
