### PR TITLE
Fix/mobile tabs styling

### PR DESCRIPTION
**Pull request by oskarrough**
Attempt to fix https://github.com/internet4000/radio4000/issues/125 and more mobile styling tweaks.

Tabs were a bit messy in the way we were using flexbox. So cleaned that. And gave `.Manchet .Tabs` a min-width to ensure it breaks on smaller screens. Otherwise it uses the same responsive now with all other tabs.

Deploy preview https://deploy-preview-129--radio4000.netlify.com/

### CODE REVIEW

**Comment by oskarrough** [comment]
screen shot 2017-11-13 at 23 15 36
screen shot 2017-11-13 at 23 16 15
screen shot 2017-11-13 at 23 16 07

**Comment by oskarrough** [comment]
Also changed tabs to no longer expand by default. That is, horizontal tabs will not take any more space than they need.

**Comment by oskarrough** [comment]
@hugurp can you check and let me know if you see  more to fix? Otherwise we can merge.

**Comment by hugurp** [comment]
Two things:

deepinscreenshot_select-area_20171119153720
deepinscreenshot_select-area_20171119153700

**Comment by oskarrough** [comment]
I fixed the first two issues you found.

The last one I'm not sure what we can do. But the screenshot is smaller than 320px (it works at 320 here) so perhaps we can leave it for now… otherwise the only thing I can think of is hiding 'Favorites' on mobile, since you already have it on your radio.

**Comment by hugurp** [comment]
I see different ways to fix the issue in the `.Tabs` being too wide and breaking the screen:

- hide `favorites` on mobile as you're right it is just a shortcut link. This solution is a quick fix, but also temporary, as if we have a tab with more items it will not work
deepinscreenshot_select-area_20171121154850

- make a vertical burger menu / select dropdown with each links (on mobile)
deepinscreenshot_select-area_20171121155103. Issue, we need to display two different templates ofr mobile and larger screens, and it does not meanthat the menu will not break on larger screens if there are more items.

- make the menu overflow horinzontaly, therefore scrollable - advantage works everywhere, inconvenient, it can be ugly on some browsers
deepinscreenshot_select-area_20171121155436

**Comment by hugurp** [comment]
I would actually remove the `.Tabs` styling I did for the channel route, and use the classic one. In a `.Container.Container--noPaddingMobile` with `max-width: 100vw` and `overflow-x: scroll`
deepinscreenshot_select-area_20171121160412

**Comment by oskarrough** [comment]
OK! Good thoughts, thanks. I like your last solution where we keep the menu items visible. Pushed.

**Comment by oskarrough** [comment]
@hugurp can you review one more time pretty please

**Comment by oskarrough** [comment]
There is some padding-left on the `.Manchet h1` which makes it not left align. Perhaps it's for the burger?

**Comment by hugurp** [comment]
Not sure what is going on osk
deepinscreenshot_select-area_20171123000050

**Comment by hugurp** [comment]
Also not sure what happens with the manchet, there should only be padding left when the aside is closed, so there is space for the aside toggle button. Somehting must have been removed somewhere.

**Comment by oskarrough** [comment]
This is without padding. Perhaps we can just remove all padding left there?

screen shot 2017-11-23 at 00 49 14

Other thing was my mistake. Didn't see it since my channel title was long……

**Pull request merged**
