### PR TITLE
Upgrade ember cli

### PR DESCRIPTION
**Pull request by oskarrough**
This PR upgrades to 2.18. It doesn't go directly to 3.0 because there are some deprecations from addons we need to wait for - or help them update as well.

- [x] update ember-cli-stripe
- [x] update ember-leaflet
- [x] update ember-cp-validations

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-cli-stripe -> ember-invoke-action -> ember-cli-babel
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/~radio4000/node_modules/ember-invoke-action/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-cp-validations -> ember-require-module -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-leaflet -> ember-composability-tools -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-leaflet -> ember-composability-tools -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-leaflet -> ember-composability-tools -> ember-wormhole -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-leaflet -> ember-get-config -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: radio4000 -> ember-leaflet -> ember-invoke-action -> ember-cli-babel
```

### CODE REVIEW

**Comment by oskarrough** [comment]
Things seem fixed in ember-cli-stripe#master. Waiting for release… Then we can merge.

There's also some new deprecation that you can not import and inline .css files via node-sass, as weird as that sounds. Can be fixed another time, but we have to remember before eventually upgrading node-sass.

**Comment by hellerve** [comment]
As for the SASS issue: could you not just rename all CSS files to SASS and be done? It’s backwards-compatible, right? Or do you need to pass in some vendored CSS files?

**Comment by oskarrough** [comment]
Hmmm.. good idea. It is the vendor CSS that is causing trouble: https://github.com/internet4000/radio4000/blob/upgrade-ember-cli/app/styles/app.scss#L7-L10.

Maybe there are SCSS variants available, I'll check.

**Comment by oskarrough** [comment]
@hellerve I opened https://github.com/internet4000/radio4000/pull/231 which removes replaces two only .css libraries we were importing.

**Pull request merged**
