### PR TITLE
Hide 'add my radio' on map when logged out

### PR DESCRIPTION
**Pull request by lucho1112**
See title

### CODE REVIEW

**Comment by hugurp** [comment]
@oskarrough I failed to see the `package-lock.json`, which adds `14,823` locs to the commits history / stats. What should have I done.

**Comment by oskarrough** [comment]
@hugurp good question. I found https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files.

- It is kind of safe to have both. Each tool will ignore the other one's lock file.
- Running `yarn` won't update the npm lock and vice versa. They will get out of sync unless we use tooling or manually update both.

I vote what he said in Stackoverflow:

> We only use Yarn as our official Node package manager, and so we will only commit yarn.lock files, and ignore package-lock.json files.

So remove it, add to gitignore and update readme's examples to recommend yarn?

**Comment by hugurp** [comment]
Ok, thanks for the light.
Not sure I still understand all that mess.

Is it good that we force all collaborators to have yarn installed?

**Comment by oskarrough** [comment]
We don't force but recommend yarn. I found this comment:

> The safest thing to do would be to generate and commit them both every time your dependencies change. However, this might well be cumbersome or the two files might get out-of-sync.

If we only commit one of them to repo we won't have to think about them getting out of sync. You can still use NPM all you want. The lock file will just be ignored by git. By having just one we're also sure that the same gets installed on Travis and Netlify,

**Pull request merged**
