### PR TITLE
add basic spam protection

### LINKED ISSUE #131: Add basic spam protection to feedback form
```
<form>
  <p style="display:none;">
    <label>Don’t fill this out: <input name="bot-field"></label>
  </p>
```

from here: https://www.netlify.com/blog/2017/11/09/form-handling-update-deleting-submissions/

### PR DESCRIPTION
**Pull request by hugurp**
let's see if that really really works
fixes #131

### CODE REVIEW

**Comment by oskarrough** [comment]
I think this is meant to work only if you send the data to the Netlify form thing?

**Comment by hugurp** [comment]
Ok. So what do we do?
Why would't it work here?

**Comment by oskarrough** [comment]
Hmm.. because we are not sending our form to Netlify but Google.

The way I (know) understand Netlify's form handling is that they parse your static HTML deploys and search for `form[data-netlify]` and dynamically set up the form backend stuff. Which also handles the spam protection. It doesn't find form elements in react/ember etc. so you have to do this https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/.

So if spam protection is important we should find some other (vanilla) way of doing it? Or does the google app script have something?

**Comment by hugurp** [comment]
If the botfield is not empty then the form won't submit, that is all that does here.

**Comment by oskarrough** [comment]
Aaah, now I understand…… missed that part in our own code sorry. No idea if bots fall for that but if so it's a very nice little trick!

**Comment by hugurp** [comment]
Glad you realize I am not as stupid as addind a `netlify` class to an input to implement spam protection.

**Pull request merged**
