### PR TITLE
Remove ember-service-worker

### PR DESCRIPTION
**Pull request by oskarrough**
I don't want to remove the service worker, but it is what seems to be the quickest fix for https://github.com/internet4000/radio4000/issues/499.

### CODE REVIEW

**Comment by oskarrough** [comment]
Did not solve the issue. Hard-refreshing always works, but normal F5 or cmd+r does not.

**Comment by hugurp** [comment]
I don't see any issue with the radio4000.com live version on webkit browsers; but received many complain sms

**Comment by oskarrough** [comment]
I see this 

screen 2021-11-24 at 11 23 47@2x

if I hard-refresh, it works. But as soon as I refresh or visit in another tab, it breaks again.

Merging for now, then we can add our own PWA service-worker without any ember addons :)

**Comment by hugurp** [comment]
nicely done, yep, let's simplify!

**Comment by hugurp** [comment]
Maybe it was something like that https://love2dev.com/blog/how-to-uninstall-a-service-worker/

When i open in chromium, it works if I `unregister the service worker`, then works accross refreshes

**Pull request merged**
