### PR TITLE
Feature/keyboard shortcuts v2

### LINKED ISSUE #87: Keyboard shortcuts (with radio4000-player)
Shortcuts have to be re-implemented because they broke when we externalized the player on radio4000.com to a vue.js app to use it as npm module, web-component and iframe.

Figure out the best way to handle **shortcuts** across the two apps on the site, ember and player-vue.

Shortcuts can also be good to restructure some part of the apps in functions, making the general api clearer.

See post below for summary

### PR DESCRIPTION
**Pull request by hugurp**
Add keyboard shortcuts for cms navigation.

For details, look inside `/mixins/keyboard-shortcuts-global`.
https://github.com/internet4000/radio4000/blob/e47266e8b13215cc19bf593736703786c55bc310/app/mixins/keyboard-shortcuts-global.js

Closes #87 (partially, has the rest as to be implement when we have a good search, and or `radio4000-player`)

### CODE REVIEW

**Comment by hugurp** [comment]
Not sure how to writte test for that

**Comment by oskarrough** [comment]
I think it could be an acceptance test + `keyEvent` helper from here https://guides.emberjs.com/v2.16.0/testing/acceptance/#toc_asynchronous-helpers. So we navigate to one page, trigger the shortcut, wait for page transition, verify we're on the new route. And another test where the buttons are pressed too slow.

Looks really nice!! I would love the `?` shortcut like on github to get an overview 📟

**Comment by hugurp** [comment]
ok tests in an other life

**Comment by hugurp** [comment]
and for `?`, would be nice, but https://github.com/patience-tema-baron/ember-keyboard/issues/71

**Pull request merged**
