### PR TITLE
Feature/player vue

### PR DESCRIPTION
**Pull request by hugurp**
This PR switches the player to be using https://github.com/internet4000/radio4000-player-vue

Why?
- one player to maintain
- player can be used in r4 and outside r4, by internal and external projects (embed, mix...)
- player could be used with r4 data or other data sources

To be solved:

- [x] `channel-card` `play-then-shuffle` button needs `radio4000`to maintain some kind of "shuffle state or function"
- [x] add player events for history
- [x] `active track` and played tracks
- [x] `active channel`
- [x] fix playing history
- [x] test whether it plays in newest Safari, Firefox, Chrome and Edge as well as mobile (@Oskar)
- [x] make tests pass
- [x] load radio4000-player from npm package
- [ ] ~~test whether it plays in newest Edge as well as mobile (@Oskar)~~

### CODE REVIEW

**Comment by hugurp** [comment]
Are we still doing this or not?
I think we should.
Opinions or status?

**Comment by oskarrough** [comment]
We are doing it!

I just merged firebase+shuffle in the vue player. The Firebase change should hopefully also fix the wrong-image issue.

What are we still missing?

**Comment by hugurp** [comment]
we're missing the non checked todo in the original post.
If you see nanything else, please edit the message and add a todo.
And for open todos, could you tell me what your opinion is? :]

**Comment by oskarrough** [comment]
yes!

I'lll make a quick test across browsers and mobile. Can we skip the 'track ended' since we removed 'history'?

**Comment by oskarrough** [comment]
Regarding browser support we have to be aware of 'web component' support: https://github.com/karol-f/vue-custom-element#browsers-support

**Comment by oskarrough** [comment]
Works in Safari 10 + Chrome 59 + Firefox 54 on desktop. Can test mobile when I'm back but I'll check off the x-browser for now anyway.

**Comment by oskarrough** [comment]
let's merge @hugurp ?

**Pull request merged**
