### PR TITLE
improve query tracks from channel, faster?

### PR DESCRIPTION
**Pull request by hugurp**

### CODE REVIEW

**Comment by oskarrough** [comment]
OK. Here are some very unscientific load time tests on /good-time-radio. All in Chrome on localhost throttled to "Slow 3G". I emptied the tracks template so the times do not include actually rendering the list.

```js
// Version 0
// no tracks loaded, only channel
```

- finish: around 4.4-4.6s.

```js
// Version 1
const channel = this.modelFor('channel');
return channel.get('tracks')
```

- model hook: 3000ms, 1541, 1467, 1449, 3410, 1691, 2549, 1600
- finish:  17s, 6.4, 6.3, 7.83, 8.3, 7, 7.6, 7.19

```js
// Version 2
const channel = this.modelFor('channel');
return this.store.query('track', {
  orderBy: 'channel',
  equalTo: channel.id
})
```

- model: 1565ms, 1340, 1272, 1274, 1750, 1230, 1304
- finish: 12s, 7, 9.7, 12, 6.9, 6.4, 6.37, 6.53, 7.25, 6.53

```js
// Version 3
// no model hook - emberfire decides
```

- finish: 4.5s, 4.7, 4.6, 5.1, 4.6

According to this it is fastest not to define any model hook and thereby letting Emberfire load them?

**Comment by hugurp** [comment]
what is the last solution about, I don't udnerstand

**Comment by oskarrough** [comment]
The last solution is without writing our own model hook. Since the data is already available through `channel.tracks`.

**Comment by hugurp** [comment]
closing it because results are no enough probing

**Pull request closed without merging**
