### PR TITLE
Improve play buttons

### PR DESCRIPTION
**Pull request by oskarrough**
The goal of this PR is to add an indicator to our play buttons while it's loading.

- play methods moved together in player:service as tasks
- `{{play-btn}}` is reused for `{{play-btn-shuffle}}` and `{{play-random-channel}}`
- because of that, they all have a `clickTask` available
- this `clickTask` abstracts away whichever task they actually call
- the class `is-running` is added to the buttons while the task is running/loading

**Questions**

How do we make it obvious that it is loading in each button? I tried some different things but it's not quite smooth yet.

It's a bit annoying that the focus outline-styles appear as you're tapping the button. It should only come on focus.

Anything else?

Preview: http://feature-play-buttons--radio4000.netlify.com/

### CODE REVIEW

**Comment by oskarrough** [comment]
Just noticed that https://github.com/DockYard/ember-async-button#deprecated is deprecated. We're only using it in one place so I'll replace it with ember concurrency? @hugurp

**Comment by hugurp** [comment]
WOW really sweet!
Ember concurency is really practicle, glad we're using it.

**Comment by hugurp** [comment]
I think it looks an feels really good!
Maybe on the `/$channelSlug` route, the `listen` and `play next random` animation is a little too huge? Myabe a little more transaprent?

Otherwise, and in any case, LGTM

**Comment by oskarrough** [comment]
@hugurp yes agree. For now I've disabled the pulse-animation if `showText` is true? So the pulse is only there for small-icon buttons.

**Pull request merged**
